# only add the configs not present in the base module
baseURL = 'http://docs.kcp.io/kcp'
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableMissingTranslationPlaceholders = true
enableRobotsTXT = true
enableGitInfo = true

[languages]
[languages.en]
title = 'kcp - a multi-tenant control plane for Kubernetes APIs'
description = "kcp documentation"
languageName = "English"
weight = 1


[params]
copyright = "The kcp Authors"
#version-start
archived_version = false
version = "main"
#version-end
version_menu = "Releases"
version_menu_pagelinks = true
url_latest_version = "https://kcp-dev.github.io/kcp/main"
github_repo = "https://github.com/kcp-dev/kcp"
github_project_repo = "https://github.com/kcp-dev/kcp"
github_subdir = "docs"
github_branch = "main"


# hugo module configuration
[module]
[[module.imports]]
path = "github.com/avinal/hugo-base-module"
disabled = false
ignoreConfig = false
ignoreImports = true
[[module.imports.mounts]]
source = "assets"
target = "assets"
[[module.imports.mounts]]
source = "layouts"
target = "layouts"
[[module.imports.mounts]]
source = "static"
target = "static"
[module.hugoVersion]
extended = true
min = "0.75.0"
[[module.imports]]
path = "github.com/google/docsy"
disable = false
[[module.imports]]
path = "github.com/google/docsy/dependencies"
disable = false

# release versions

[[params.versions]]
version = "main"
url = "https://kcp-dev.github.io/kcp/main"
